"""Add FAP models and telemetry columns

Revision ID: 06c0abfe914c
Revises: a9a977bc4a1a
Create Date: 2026-04-12 12:44:58.902813

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '06c0abfe914c'
down_revision: Union[str, None] = 'a9a977bc4a1a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('functionalities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_functionalities_id'), 'functionalities', ['id'], unique=False)
    op.create_index(op.f('ix_functionalities_name'), 'functionalities', ['name'], unique=True)
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('ad_group_mapping', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_roles_id'), 'roles', ['id'], unique=False)
    op.create_index(op.f('ix_roles_name'), 'roles', ['name'], unique=True)
    op.create_table('role_functionalities',
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('functionality_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['functionality_id'], ['functionalities.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('role_id', 'functionality_id')
    )
    op.create_table('user_roles',
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'role_id')
    )
    op.add_column('servers', sa.Column('cpu_usage', sa.String(), nullable=True))
    op.add_column('servers', sa.Column('mem_usage', sa.String(), nullable=True))
    op.add_column('servers', sa.Column('patch_level', sa.String(), nullable=True))
    op.add_column('servers', sa.Column('last_heard', sa.DateTime(timezone=True), nullable=True))
    op.add_column('servers', sa.Column('agent_endpoint', sa.String(), nullable=True))
    op.add_column('servers', sa.Column('agent_secret', sa.String(), nullable=True))
    op.add_column('services', sa.Column('current_image', sa.String(), nullable=True))
    op.add_column('services', sa.Column('base_image_version', sa.String(), nullable=True))
    op.add_column('services', sa.Column('last_version_deployed', sa.String(), nullable=True))
    op.add_column('services', sa.Column('last_deployed_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('services', sa.Column('last_deployed_by', sa.String(), nullable=True))
    op.add_column('services', sa.Column('health_status', sa.String(), nullable=True))
    op.add_column('services', sa.Column('telemetry_metadata', sa.JSON(), nullable=True))
    op.add_column('ske_services', sa.Column('current_image', sa.String(), nullable=True))
    op.add_column('ske_services', sa.Column('base_image_version', sa.String(), nullable=True))
    op.add_column('ske_services', sa.Column('last_version_deployed', sa.String(), nullable=True))
    op.add_column('ske_services', sa.Column('last_deployed_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('ske_services', sa.Column('last_deployed_by', sa.String(), nullable=True))
    op.add_column('ske_services', sa.Column('health_status', sa.String(), nullable=True))
    op.add_column('ske_services', sa.Column('telemetry_metadata', sa.JSON(), nullable=True))
    
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('auth_source', sa.Enum('local', 'ad', name='authsource'), nullable=False, server_default='local'))
        batch_op.add_column(sa.Column('is_external', sa.Boolean(), nullable=False, server_default='0'))
        batch_op.add_column(sa.Column('last_login', sa.DateTime(timezone=True), nullable=True))
        batch_op.alter_column('hashed_password',
                   existing_type=sa.VARCHAR(),
                   nullable=True)
        batch_op.drop_column('role')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Use batch_alter_table for SQLite compatibility
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role', sa.VARCHAR(length=9), nullable=False, server_default='viewer'))
        batch_op.alter_column('hashed_password',
                   existing_type=sa.VARCHAR(),
                   nullable=False)
        batch_op.drop_column('last_login')
        batch_op.drop_column('is_external')
        batch_op.drop_column('auth_source')

    op.drop_column('ske_services', 'telemetry_metadata')
    op.drop_column('ske_services', 'health_status')
    op.drop_column('ske_services', 'last_deployed_by')
    op.drop_column('ske_services', 'last_deployed_at')
    op.drop_column('ske_services', 'last_version_deployed')
    op.drop_column('ske_services', 'base_image_version')
    op.drop_column('ske_services', 'current_image')
    op.drop_column('services', 'telemetry_metadata')
    op.drop_column('services', 'health_status')
    op.drop_column('services', 'last_deployed_by')
    op.drop_column('services', 'last_deployed_at')
    op.drop_column('services', 'last_version_deployed')
    op.drop_column('services', 'base_image_version')
    op.drop_column('services', 'current_image')
    op.drop_column('servers', 'agent_secret')
    op.drop_column('servers', 'agent_endpoint')
    op.drop_column('servers', 'last_heard')
    op.drop_column('servers', 'patch_level')
    op.drop_column('servers', 'mem_usage')
    op.drop_column('servers', 'cpu_usage')
    op.drop_table('user_roles')
    op.drop_table('role_functionalities')
    op.drop_index(op.f('ix_roles_name'), table_name='roles')
    op.drop_index(op.f('ix_roles_id'), table_name='roles')
    op.drop_table('roles')
    op.drop_index(op.f('ix_functionalities_name'), table_name='functionalities')
    op.drop_index(op.f('ix_functionalities_id'), table_name='functionalities')
    op.drop_table('functionalities')
    # ### end Alembic commands ###
