"""Add AI Audit Log table

Revision ID: 9dc09ced7ea6
Revises: 0b9188fc69bf
Create Date: 2026-04-15 01:35:59.917630

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9dc09ced7ea6'
down_revision: Union[str, None] = '0b9188fc69bf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
